version: '3.8'
services:
  db:
    image: postgres:14-alpine
    container_name: hapi-test-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hapitest
    ports:
      - '5432:5432'
