from datetime import datetime

data_operational_presence = [
    dict(
        id=1,
        resource_ref=1,
        admin2_ref=2,
        org_ref=1,
        sector_code="SHL",
        reference_period_start=datetime(2023, 1, 1),
        reference_period_end=None,
        source_data="DATA,DATA,DATA",
    ),
    dict(
        id=2,
        resource_ref=1,
        admin2_ref=4,
        org_ref=2,
        sector_code="FSC",
        reference_period_start=datetime(2023, 1, 1),
        reference_period_end=None,
        source_data="DATA,DATA,DATA",
    ),
    dict(
        id=3,
        resource_ref=1,
        admin2_ref=4,
        org_ref=3,
        sector_code="WSH",
        reference_period_start=datetime(2023, 1, 1),
        reference_period_end=None,
        source_data="DATA,DATA,DATA",
    ),
    dict(
        id=4,
        resource_ref=1,
        admin2_ref=6,
        org_ref=3,
        sector_code="HEA",
        reference_period_start=datetime(2023, 1, 1),
        reference_period_end=None,
        source_data="DATA,DATA,DATA",
    ),
    dict(
        id=5,
        resource_ref=1,
        admin2_ref=1,
        org_ref=2,
        sector_code="WSH",
        reference_period_start=datetime(2023, 1, 1),
        reference_period_end=None,
        source_data="DATA,DATA,DATA",
    ),
]
