from datetime import datetime

data_admin2 = [
    dict(
        admin1_ref=1,
        code="FOO-XXX-XXX",
        name="Unspecified",
        is_unspecified=True,
        reference_period_start=None,
        reference_period_end=None,
        hapi_updated_date=datetime(2023, 1, 1),
        hapi_replaced_date=None,
    ),
    dict(
        admin1_ref=2,
        code="FOO-001-XXX",
        name="Unspecified",
        is_unspecified=True,
        reference_period_start=None,
        reference_period_end=None,
        hapi_updated_date=datetime(2023, 1, 1),
        hapi_replaced_date=None,
    ),
    dict(
        admin1_ref=3,
        code="FOO-002-XXX",
        name="Unspecified",
        is_unspecified=True,
        reference_period_start=None,
        reference_period_end=None,
        hapi_updated_date=datetime(2023, 1, 1),
        hapi_replaced_date=None,
    ),
    dict(
        admin1_ref=2,
        code="FOO-001-A",
        name="District A",
        is_unspecified=False,
        reference_period_start=None,
        reference_period_end=None,
        hapi_updated_date=datetime(2023, 1, 1),
        hapi_replaced_date=None,
    ),
    dict(
        admin1_ref=2,
        code="FOO-001-B",
        name="District B",
        is_unspecified=False,
        reference_period_start=None,
        reference_period_end=None,
        hapi_updated_date=datetime(2023, 1, 1),
        hapi_replaced_date=None,
    ),
    dict(
        admin1_ref=3,
        code="FOO-002-C",
        name="District C",
        is_unspecified=False,
        reference_period_start=None,
        reference_period_end=None,
        hapi_updated_date=datetime(2023, 1, 1),
        hapi_replaced_date=None,
    ),
]
